# Generated by Django 2.0.2 on 2018-02-08 20:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'uno'), ('2', 'dos'), ('3', 'tres'), ('4', 'cuatro'), ('5', 'cinco')], default=' ', max_length=9)),
                ('design', multiselectfield.db.fields.MultiSelectField(choices=[('6', 'uno'), ('7', 'dos'), ('8', 'tres'), ('9', 'cuatro'), ('10', 'cinco')], default=' ', max_length=10)),
                ('more_like', models.CharField(default=' ', max_length=100)),
                ('price', multiselectfield.db.fields.MultiSelectField(choices=[('11', 'uno'), ('12', 'dos')], default=' ', max_length=5)),
            ],
        ),
    ]
