# Generated by Django 2.0.2 on 2018-02-10 16:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='design',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('6', '2'), ('7', '4'), ('8', '6'), ('9', '8'), ('10', '10')], default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='like',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '2'), ('2', '4'), ('3', '6'), ('4', '8'), ('5', '10')], default=' ', max_length=9),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='price',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('11', 'malo'), ('12', 'bueno')], default=' ', max_length=5),
        ),
    ]
