# Generated by Django 2.0.2 on 2018-02-10 20:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180210_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='price',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='price_bad',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('12', 'Mal')], default=' ', max_length=2),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='price_god',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('11', 'Bien')], default=' ', max_length=2),
        ),
    ]
